In [1]:


import numpy as np



a = np.array([[1, 2], [3, 4]])

print(a.shape)

a.shape = (1, 4)

print(a)

a = a.reshape(-1, 1)

print(a)

inp = '1 2 3 4 5 6 7 8 9'
arr = np.array([int(k) for k in inp.strip().split(' ')]).reshape(3, 3)
print(arr)

(2, 2)
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:

a = np.array([[1, 2, 3, 4]])

b = np.transpose(a)

print(a, b)

c = a.reshape((2, 2))

print(c)

d = c.flatten()

print(d)

[[1 2 3 4]] [[1]
 [2]
 [3]
 [4]]
[[1 2]
 [3 4]]
[1 2 3 4]
