In [4]:

import os
import numpy as np
import brotli

bin_path = '/home/lokesh/temp/output/pointIndexMap.bin'

with open(bin_path, 'rb') as in_file:
    compressed_data = in_file.read()

print(len(compressed_data))

data = brotli.decompress(compressed_data)

arr = np.frombuffer(data, dtype=np.int16)

counts = np.bincount(arr)

print(np.sum(counts))

print(len(arr))

print(arr)

print(np.unique(arr))

print(counts)


54504546
160024826
160024826
[2984 7509 7506 ... 7507 6711 6711]
[   0    1    2 ... 7509 7510 7511]
[  199     2     3 ...  7369   147 11715]


In [1]:

import numpy as np
import brotli

data = np.array([i for i in range(10000)], dtype=np.int32).tobytes()
print(len(data))

compressed_data = brotli.compress(data)

print(len(compressed_data))

data = brotli.decompress(compressed_data)

print(len(data))

data = np.frombuffer(data, dtype=np.int32)

print(data[:5])

40000
9602
40000
[0 1 2 3 4]
