In [1]:


import numpy as np



a = np.array([[1, 2], [3, 4]])

print(a.shape)

a.shape = (1, 4)

print(a)

a = a.reshape(-1, 1)

print(a)

inp = '1 2 3 4 5 6 7 8 9'
arr = np.array([int(k) for k in inp.strip().split(' ')]).reshape(3, 3)
print(arr)

(2, 2)
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:

a = np.array([[1, 2, 3, 4]])

b = np.transpose(a)

print(a, b)

c = a.reshape((2, 2))

print(c)

d = c.flatten()

print(d)

[[1 2 3 4]] [[1]
 [2]
 [3]
 [4]]
[[1 2]
 [3 4]]
[1 2 3 4]


In [13]:


a = np.array([1,2,3])
print(np.concatenate((a, a)))

a = np.identity(2)
print(np.concatenate((a, a), axis=1))


# n, m, p = [int(k) for k in input().split(' ')]

# a1 = np.empty((n, p))
# for i in range(n):
#     a1[i] = [int(k) for k in input().split(' ')]
# a2 = np.empty((m, p))
# for i in range(m):
#     a2[i] = [int(k) for k in input().split(' ')]

# print(np.concatenate((a1, a2), axis=0))


print(np.identity(2))

print(np.eye(8, 7, k=1))
print(np.eye(8, 7, k=2))

[1 2 3 1 2 3]
[[1. 0. 1. 0.]
 [0. 1. 0. 1.]]
[[1. 0.]
 [0. 1.]]
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [11]:
## Polynomials using NumPy

import numpy as np

# create polynomial using the roots
print(np.poly([-1, 1]))

# get roots of polynomial
print(np.roots([1, 0, -2]))

# indefinite integral or antiderivative of polynomial
print(np.polyint([1, 2, 3]))

# derivative
print(np.polyder([1, 2, 3]))

# evaluate polynomial at a value
print(np.polyval([1, 2, 3], 4))

# fit a polynomial of given order to a set of data using least-squares
print(np.polyfit([0, 1, 2, 3, 4], [0, 1, 4, 9, 16], 3))




[ 1.  0. -1.]
[-1.41421356  1.41421356]
[0.33333333 1.         3.         0.        ]
[2 2]
27
[ 2.82392982e-16  1.00000000e+00  4.21611975e-15 -3.97205465e-15]


In [5]:
import numpy as np


i = np.identity(2)

# determinant
print(np.linalg.det(i))


# eigen values and eigen vectors
arr = np.array([[1, 2], [3, 4]])
eigen_values, eigen_vectors = np.linalg.eig(arr)
print(eigen_values, eigen_vectors)

# invesrse
print(np.linalg.inv(arr))


1.0
[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[[-2.   1. ]
 [ 1.5 -0.5]]
