In [2]:
import torch
import numpy as np

In [3]:


x = torch.rand(3)

print(x)

torch.cuda.is_available()

x = torch.empty(1)
print(x)
x = torch.empty(3, 3)
print(x)

x = torch.rand(2, 2)
print(x)

x = torch.ones(2, 2, dtype=torch.int)
print(x)

print(x.dtype)

x = torch.tensor([3, 2, 4, 3])
print(x)

y = torch.rand(4, 1)

z = x + y

print(y)
print(z)

z = torch.add(x, y)
print(z)

y = torch.rand(x.shape)
y.add_(x)
print(y)

z = torch.sub(x, y)
print(z)

z = torch.mul(x, y)
print(z)

z = torch.div(x, y)
print(z)

x = torch.rand(5, 3)
print(x[:, :2])

print(x[0, 0].item())

y = x.view(3, 5)
print(y)
z = x.view(15)
print(z)



tensor([0.9259, 0.7371, 0.7562])
tensor([5.3291e-19])
tensor([[-2.4219e-16,  4.5682e-41, -2.4219e-16],
        [ 4.5682e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00,  5.2750e-19]])
tensor([[0.2543, 0.1189],
        [0.0958, 0.0891]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32
tensor([3, 2, 4, 3])
tensor([[0.4362],
        [0.6460],
        [0.6834],
        [0.6813]])
tensor([[3.4362, 2.4362, 4.4362, 3.4362],
        [3.6460, 2.6460, 4.6460, 3.6460],
        [3.6834, 2.6834, 4.6834, 3.6834],
        [3.6813, 2.6813, 4.6813, 3.6813]])
tensor([[3.4362, 2.4362, 4.4362, 3.4362],
        [3.6460, 2.6460, 4.6460, 3.6460],
        [3.6834, 2.6834, 4.6834, 3.6834],
        [3.6813, 2.6813, 4.6813, 3.6813]])
tensor([3.3505, 2.5225, 4.8685, 3.1897])
tensor([-0.3505, -0.5225, -0.8685, -0.1897])
tensor([10.0516,  5.0451, 19.4740,  9.5692])
tensor([0.8954, 0.7929, 0.8216, 0.9405])
tensor([[0.5251, 0.4810],
        [0.9943, 0.1681],
        [0.2703, 0.6794],

In [4]:

a = torch.ones(4)

b = a.numpy()

print(b)

a.add_(1)
print(a)
print(b)

print(a.device)

a = np.ones(4)
b = torch.from_numpy(a)
c = torch.Tensor(a)
a += 1
print(b, c)

print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(4, device = device)
    print(x)
    print(x.device)
    y = torch.ones(4)
    y = y.to(device)
    z = x + y
#     z.numpy() #error
    z_cpu = z.to('cpu')
    print(z_cpu)

x = torch.ones(5, requires_grad=True)

print(x)



[1. 1. 1. 1.]
tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]
cpu
tensor([2., 2., 2., 2.], dtype=torch.float64) tensor([1., 1., 1., 1.])
True
tensor([1., 1., 1., 1.], device='cuda:0')
cuda:0
tensor([2., 2., 2., 2.])
tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [36]:

x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
z = z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)

z = y * y * 2
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)


with torch.no_grad():
    y = x + 2
    print(y)

x.requires_grad_(False)
y = x + 2
print(y)
# x.detach()


weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step()
# optimizer.zero_grad()


tensor([-0.5870,  1.3946, -1.9238], requires_grad=True)
tensor([1.4130, 3.3946, 0.0762], grad_fn=<AddBackward0>)
tensor(9.0173, grad_fn=<MeanBackward0>)
tensor([1.8840, 4.5262, 0.1016])
tensor([ 2.4493, 18.1047,  0.1019])
tensor([1.4130, 3.3946, 0.0762])
tensor([1.4130, 3.3946, 0.0762])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [41]:
## Backpropagation

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

y_hat = w * x

loss = (y_hat - y)**2

print(loss)

# backward pass

loss.backward()
print(w.grad)



tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [47]:
# gradients using numpy

# f = w * x = 2 * x
X = np.array([1, 2, 3, 4]).astype(np.float32)

Y = np.array([2, 4, 6, 8]).astype(np.float32)

w = 0.0

# model prediction
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_predicted):
    return ((y_predicted - y)**2).mean()

# gradient
# MSE = 1/N * (w*x - y)**2
#d3/dw = 1/N 2x(w*x - y)
def gradient(x, y, y_predicted):
    return np.dot(2*x, y_predicted - y).mean()


print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # prediction = forward
    y_pred = forward(X)
    
    #loss
    l = loss(Y, y_pred)
    
    #gradients
    dw = gradient(X,Y,y_pred)
    
    #update weights
    w -= learning_rate * dw
    
    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:3f}, loss = {l:.8f}')


print(f'Prediction after training: f(5) = {forward(5):.3f}')


Prediction before training: f(5) = 0.000
epoch 1: w = 1.200000, loss = 30.00000000
epoch 3: w = 1.872000, loss = 0.76800019
epoch 5: w = 1.979520, loss = 0.01966083
epoch 7: w = 1.996723, loss = 0.00050331
epoch 9: w = 1.999476, loss = 0.00001288
epoch 11: w = 1.999916, loss = 0.00000033
epoch 13: w = 1.999987, loss = 0.00000001
epoch 15: w = 1.999998, loss = 0.00000000
epoch 17: w = 2.000000, loss = 0.00000000
epoch 19: w = 2.000000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [50]:
# gradients using torch

# f = w * x = 2 * x
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)

Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model prediction
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_predicted):
    return ((y_predicted - y)**2).mean()


print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # prediction = forward
    y_pred = forward(X)
    
    #loss
    l = loss(Y, y_pred)
    
    #gradients
    l.backward() # dl/dw
    
    
    #update weights
    with torch.no_grad():
        w -= learning_rate * w.grad
    
    # zero gradients
    w.grad.zero_()
    
    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w:3f}, loss = {l:.8f}')


print(f'Prediction after training: f(5) = {forward(5):.3f}')


Prediction before training: f(5) = 0.000
epoch 1: w = 0.300000, loss = 30.00000000
epoch 11: w = 1.665314, loss = 1.16278565
epoch 21: w = 1.934109, loss = 0.04506890
epoch 31: w = 1.987028, loss = 0.00174685
epoch 41: w = 1.997446, loss = 0.00006770
epoch 51: w = 1.999497, loss = 0.00000262
epoch 61: w = 1.999901, loss = 0.00000010
epoch 71: w = 1.999980, loss = 0.00000000
epoch 81: w = 1.999996, loss = 0.00000000
epoch 91: w = 1.999999, loss = 0.00000000
Prediction after training: f(5) = 10.000
