In [41]:
import torch
import numpy as np

In [72]:

x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
z = z.mean()
print(z)



tensor([0.8415, 0.5952, 0.1283], requires_grad=True)
tensor([2.8415, 2.5952, 2.1283], grad_fn=<AddBackward0>)
tensor(12.8927, grad_fn=<MeanBackward0>)


In [60]:

a = torch.ones(4)

b = a.numpy()

print(b)

a.add_(1)
print(a)
print(b)

print(a.device)

a = np.ones(4)
b = torch.from_numpy(a)
c = torch.Tensor(a)
a += 1
print(b, c)

print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(4, device = device)
    print(x)
    print(x.device)
    y = torch.ones(4)
    y = y.to(device)
    z = x + y
#     z.numpy() #error
    z_cpu = z.to('cpu')
    print(z_cpu)

x = torch.ones(5, requires_grad=True)

print(x)



[1. 1. 1. 1.]
tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]
cpu
tensor([2., 2., 2., 2.], dtype=torch.float64) tensor([1., 1., 1., 1.])
True
tensor([1., 1., 1., 1.], device='cuda:0')
cuda:0
tensor([2., 2., 2., 2.])
tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [43]:


x = torch.rand(3)

print(x)

torch.cuda.is_available()

x = torch.empty(1)
print(x)
x = torch.empty(3, 3)
print(x)

x = torch.rand(2, 2)
print(x)

x = torch.ones(2, 2, dtype=torch.int)
print(x)

print(x.dtype)

x = torch.tensor([3, 2, 4, 3])
print(x)

y = torch.rand(4, 1)

z = x + y

print(y)
print(z)

z = torch.add(x, y)
print(z)

y = torch.rand(x.shape)
y.add_(x)
print(y)

z = torch.sub(x, y)
print(z)

z = torch.mul(x, y)
print(z)

z = torch.div(x, y)
print(z)

x = torch.rand(5, 3)
print(x[:, :2])

print(x[0, 0].item())

y = x.view(3, 5)
print(y)
z = x.view(15)
print(z)



tensor([0.6151, 0.2720, 0.0029])
tensor([-2.2944e+14])
tensor([[-2.2944e+14,  4.5848e-41, -1.2144e+22],
        [ 3.0638e-41,  4.4842e-44,  0.0000e+00],
        [ 1.5695e-43,  0.0000e+00, -1.2067e+22]])
tensor([[0.9572, 0.5296],
        [0.0850, 0.9943]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32
tensor([3, 2, 4, 3])
tensor([[0.4706],
        [0.9977],
        [0.2153],
        [0.8891]])
tensor([[3.4706, 2.4706, 4.4706, 3.4706],
        [3.9977, 2.9977, 4.9977, 3.9977],
        [3.2153, 2.2153, 4.2153, 3.2153],
        [3.8891, 2.8891, 4.8891, 3.8891]])
tensor([[3.4706, 2.4706, 4.4706, 3.4706],
        [3.9977, 2.9977, 4.9977, 3.9977],
        [3.2153, 2.2153, 4.2153, 3.2153],
        [3.8891, 2.8891, 4.8891, 3.8891]])
tensor([3.2569, 2.4873, 4.2605, 3.1727])
tensor([-0.2569, -0.4873, -0.2605, -0.1727])
tensor([ 9.7707,  4.9747, 17.0419,  9.5180])
tensor([0.9211, 0.8041, 0.9389, 0.9456])
tensor([[0.6724, 0.1857],
        [0.3089, 0.0494],
        [0.8947, 0.9571]