In [72]:

import torch
import numpy as np
from scipy.spatial import Delaunay


points = np.random.rand(10, 3)

points = torch.tensor(points)

# point = np.array(points[5].clone().detach()).reshape(1, -1)

# points[:, :2] = points[:, :2] - point[:, :2]

# dists = torch.norm(points[:, :3], 2, 1, keepdim=False)

# print(dists)


def in_hull(p, hull):
    """
    :param p: (N, K) test points
    :param hull: (M, K) M corners of a box
    :return (N) bool
    """
    try:
        if not isinstance(hull, Delaunay):
            hull = Delaunay(hull)
        flag = hull.find_simplex(p) >= 0
    except scipy.spatial.qhull.QhullError:
        print('Warning: not a hull %s' % str(hull))
        flag = np.zeros(p.shape[0], dtype=np.bool)

    return flag

x, y, z = 1, 1, 0.5

hull = np.array(
    [[0     ,0   ,0     ],
     [0   ,0    ,z     ],
     [0   ,y    ,0     ],
     [0    ,y    ,z     ],
     [x     ,0   ,0     ],
     [x   ,0    ,z     ],
     [x   ,y    ,0     ],
     [x    ,y    ,z     ]]
)

# print(points)

r = in_hull(points , hull)

for i in range(len(points)):
    print(points[i], r[i])

tensor([0.2292, 0.4803, 0.4177], dtype=torch.float64) True
tensor([0.1771, 0.7993, 0.1723], dtype=torch.float64) True
tensor([0.3444, 0.8791, 0.8676], dtype=torch.float64) False
tensor([0.9483, 0.5644, 0.0886], dtype=torch.float64) True
tensor([0.3261, 0.0289, 0.7789], dtype=torch.float64) False
tensor([0.9782, 0.6163, 0.1120], dtype=torch.float64) True
tensor([0.8388, 0.5011, 0.0281], dtype=torch.float64) True
tensor([0.0191, 0.0699, 0.6675], dtype=torch.float64) False
tensor([0.9292, 0.2194, 0.4994], dtype=torch.float64) True
tensor([0.5898, 0.6667, 0.0811], dtype=torch.float64) True


In [81]:


np.unique(np.random.choice(10, 20))



array([1, 2, 3, 4, 5, 6, 7, 8, 9])